### ISSUE TITLE
Comma separated numbers

### ISSUE THREAD

**Issue by tmartin31** [josecoelhomelo/counter#1]
An awesome little JS plugin. Great job! :)

I’m just wondering if there’s any way to change the format of numbers to be comma separated? For example:

1356
29830
301982

Could be displayed as:

1,356
29,830
301,982

Would this be possible or easy to implement?

Thanks!

**Comment by josecoelhomelo** [comment]
Hey, thanks! I'm sorry for the late reply, I've been a little busy.

You've probably moved on with a solution of your own but either way, I've updated the plugin to allow a callback function to run. You can pass it in options like so:
```js
new Counter('.counter', {
    origin: 20,
    target: 25000,
    suffix: '€',    
    format: (value) => value.toLocaleString()
});
```

**Comment by tmartin31** [comment]
Oh, amazing! Thanks so much and Merry Christmas. :)

**Comment by josecoelhomelo** [comment]
You're welcome! Have a great year.
